import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const template = readFileSync(
  resolve(process.cwd(), "supabase/functions/_shared/email-templates/code-email.tsx"),
  "utf8",
);

describe("authentication email template", () => {
  it("uses absolute published URLs for the light/dark full logos", () => {
    expect(template).toContain("https://www.whoop-whoop.com/WhoopWhoop_Stacked_Logo.svg");
    expect(template).toContain("https://www.whoop-whoop.com/WhoopWhoop_Dark_Logo.svg");
    expect(template).toContain('.logo-dark { display: block !important; }');
    expect(template).not.toContain('style={brand}>WHOOP! WHOOP!</Text>');
    expect(template).not.toContain('APP_ICON_URL');
  });

  // The cream email must carry the warm-black wordmark, and the dark email the
  // cream one. Swapping these once left an invisible logo on the light email.
  it("pairs each logo with the background it sits on", () => {
    expect(template).toContain(
      "const LIGHT_LOGO_URL = 'https://www.whoop-whoop.com/WhoopWhoop_Dark_Logo.svg'",
    );
    expect(template).toContain(
      "const DARK_LOGO_URL = 'https://www.whoop-whoop.com/WhoopWhoop_Stacked_Logo.svg'",
    );
  });

  it("matches the six-digit numeric code generated by authentication", () => {
    expect(template).toContain("/^[0-9]{6}$/");
    expect(template).toContain("requireAuthCode(token)");
    expect(template).toContain("export const OTP_MINUTES = 20");
  });
});